# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - SahithApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_d1cb709958ce4f31898e7189c6c317b7 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0968a4f83fe84d5db17e53ac9e782bd8 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_d1cb709958ce4f31898e7189c6c317b7 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'SahithApp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8441380d2b71407992264d8f266f5fe6 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_d1cb709958ce4f31898e7189c6c317b7 }}/appsvc/staticsite:${{ github.sha }}'